subarch: amd64
version_stamp: stormg-02-04-2025
target: livecd-stage1
rel_type: default
profile: default/linux/amd64/23.0/desktop
snapshot_treeish: bd6107dbebe71859f12618eb0669c5d110c9b076
source_subpath: default/stage3-amd64-openrc-latest.tar.xz
compression_mode: pixz
portage_confdir: /home/ben/Desktop/catalyst_stormg/config/stages
repos: /home/ben/Desktop/catalyst_stormg/overlay/var/db/repos/guru
/home/ben/Desktop/catalyst_stormg/overlay/var/db/repos/tezeta
/home/ben/Desktop/catalyst_stormg/overlay/var/db/repos/tatsh-overlay
/home/ben/Desktop/catalyst_stormg/overlay/var/db/repos/edgets
/home/ben/Desktop/catalyst_stormg/overlay/var/db/repos/steam-overlay

livecd/use:
	-aac
	compile-locales
	fbcon
	jpeg2k
	livecd
	networkmanager
	openexr
	opus
	postproc
	portaudio
	pulseaudio
	python
	vpx
	xetex
	compat
	branding
	plymouth
        widgets
	build

livecd/packages:
	app-accessibility/brltty
	app-accessibility/espeakup
	app-admin/hddtemp
	app-admin/sudo
	app-admin/syslog-ng
	app-admin/sysstat
	app-admin/testdisk
	app-arch/bzip2
	app-arch/cpio
	app-arch/dpkg
	app-arch/deb2targz
	app-arch/gzip
	app-arch/mt-st
	app-arch/p7zip
	app-arch/pbzip2
	app-arch/rpm
	app-arch/tar
	app-arch/zip
	app-arch/unrar
	app-backup/fsarchiver
	app-benchmarks/bonnie
	app-benchmarks/bonnie++
	app-benchmarks/dbench
	app-benchmarks/iozone
	app-benchmarks/stress
	app-benchmarks/tiobench
	app-cdr/dvd+rw-tools
	app-cdr/cdrtools
	app-crypt/chntpw
	app-crypt/gnupg
	app-crypt/pinentry
	app-editors/joe
	app-editors/mg
	app-editors/nano
	app-emacs/ebuild-mode
	app-emulation/cloud-init
	app-emulation/spice-vdagent
#	Fails to build...
#	app-emulation/xen-tools
	app-eselect/eselect-repository
	app-misc/colordiff
	app-misc/livecd-tools
	app-misc/mc
	app-misc/pax-utils
	app-misc/screen
	app-misc/tmux
	app-misc/wipe
	app-portage/cpuid2cpuflags
	app-portage/eix
	app-portage/genlop
	app-portage/gentoolkit
	app-portage/mirrorselect
	app-portage/portage-utils
	app-portage/pram
	app-portage/ufed
	app-shells/bash-completion
	app-shells/gentoo-bashcomp
	app-text/bibutils
	app-text/dos2unix
	app-text/ghostscript-gpl
	app-text/pdftk
	app-text/recode
	app-text/tree
	app-text/wgetpaste
	app-text/xournalpp
	app-vim/gentoo-syntax
	dev-debug/strace
	dev-lang/perl
	dev-lang/python
#	Gone until it supports python3_10
#	dev-util/kdevelop-python
	dev-vcs/git
	dev-vcs/subversion
	media-gfx/fbgrab
	media-gfx/gimp
	media-gfx/graphviz
	media-gfx/hugin
	media-gfx/inkscape
	media-gfx/povray
	media-sound/alsa-utils
	media-video/mpv
	net-analyzer/iptraf-ng
	net-analyzer/nmap
	net-analyzer/openbsd-netcat
	net-analyzer/tcpdump
	net-analyzer/tcptraceroute
	net-analyzer/traceroute
	net-dialup/minicom
	net-dialup/mingetty
	net-dialup/pptpclient
	net-dialup/rp-pppoe
	net-dns/bind-tools
	net-fs/cifs-utils
	net-fs/nfs-utils
	net-ftp/ftp
	net-ftp/ncftp
	net-im/pidgin
	net-irc/hexchat
	net-irc/irssi
	net-irc/quassel
	net-irc/weechat
	net-misc/chrony
	net-misc/chrony
	net-misc/dhcpcd
	net-misc/iputils
	net-misc/ndisc6
	net-misc/openssh
	net-misc/rdate
	net-misc/rdesktop
	net-misc/rsync
	net-misc/telnet-bsd
	net-misc/vconfig
	net-misc/wget
	net-misc/whois
	net-proxy/dante
	net-proxy/tsocks
	net-vpn/networkmanager-openvpn
	net-vpn/networkmanager-pptp
	net-vpn/openfortivpn
	net-vpn/openvpn
	net-vpn/tor
	net-wireless/b43-fwcutter
	net-wireless/iw
	net-wireless/wireless-tools
	net-wireless/wpa_supplicant
	sys-apps/arch-chroot
	sys-apps/arrayprobe
	sys-apps/acl
	sys-apps/attr
	sys-apps/busybox
	sys-apps/cciss_vol_status
	sys-apps/chname
	sys-apps/coreutils
	sys-apps/dcfldd
	sys-apps/diffutils
	sys-apps/dmidecode
	sys-apps/dstat
	sys-apps/ethtool
	sys-apps/file
	sys-apps/findutils
	sys-apps/flashrom
	sys-apps/fxload
	sys-apps/gawk
	sys-apps/gptfdisk
	sys-apps/hdparm
	sys-apps/hwinfo
	sys-apps/ipmitool
	sys-apps/iproute2
	sys-apps/inxi
	sys-apps/less
	sys-apps/man-db
	sys-apps/man-pages
	sys-apps/man-pages-posix
	sys-apps/memtester
	sys-apps/memtest86+
	sys-apps/mlocate
	sys-apps/netplug
	sys-apps/nvme-cli
	sys-apps/pciutils
	sys-apps/pcmciautils
	sys-apps/pv
	sys-apps/sdparm
	sys-apps/sed
	sys-apps/setserial
	sys-apps/sg3_utils
	sys-apps/smartmontools
	sys-apps/which
	sys-apps/usbutils
	sys-apps/util-linux
	sys-auth/ssh-import-id
	sys-block/aoetools
	sys-block/fio
	sys-block/gparted
	sys-block/mtx
	sys-block/open-iscsi
	sys-block/parted
	sys-block/partimage
	sys-block/tw_cli
	sys-block/whdd
	sys-boot/efibootmgr
	sys-boot/grub
	sys-firmware/b43-firmware
	sys-firmware/ipw2100-firmware
	sys-firmware/ipw2200-firmware
	sys-fs/bcache-tools
	sys-fs/bcachefs-tools
	sys-fs/btrfs-progs
	sys-fs/cryptsetup
	sys-fs/ddrescue
	sys-fs/dmraid
	sys-fs/dosfstools
	sys-fs/e2fsprogs
	sys-fs/exfat-utils
	sys-fs/extundelete
	sys-fs/fuse-exfat
	sys-fs/f2fs-tools
	sys-fs/genfstab
	sys-fs/growpart
	sys-fs/jfsutils
	sys-fs/lsscsi
	sys-fs/lvm2
	sys-fs/mac-fdisk
	sys-fs/mdadm
	sys-fs/multipath-tools
	sys-fs/ntfs3g
	sys-fs/reiserfsprogs
	sys-fs/squashfs-tools
	sys-fs/xfsdump
	sys-fs/xfsprogs
	sys-kernel/dracut
	sys-kernel/installkernel
	sys-kernel/linux-firmware
	sys-libs/gpm
	sys-power/acpid
	sys-process/htop
	sys-process/lsof
	sys-process/iotop
	sys-process/procps
	sys-process/psmisc
	www-client/chromium
	www-client/firefox
	www-client/links
	x11-misc/lightdm-gtk-greeter
	x11-misc/lightdm
 	gnome-base/gnome-common
  	sys-auth/polkit
   	gnome-extra/polkit-gnome
	xfce-base/thunar-volman
	xfce-extra/thunar-archive-plugin
	xfce-extra/thunar-media-tags-plugin
	xfce-extra/xfce4-mailwatch-plugin
	xfce-extra/xfce4-pulseaudio-plugin
	xfce-extra/xfce4-weather-plugin
	xfce-extra/xfce4-whiskermenu-plugin
	xfce-extra/xfce4-panel-profiles
	x11-misc/xdg-user-dirs
	sys-process/htop
	sys-process/cronie
	net-wireless/blueman
	net-wireless/bluez
	net-print/cups
	net-print/gutenprint
	net-print/hplip
	app-admin/system-config-printer
	net-misc/ntp
	net-fs/samba
	media-sound/pavucontrol
	media-fonts/terminus-font
	gnome-extra/nm-applet
	gnome-base/gvfs
	app-arch/engrampa
	app-admin/syslog-ng
 	xfce-base/xfce4-meta
	x11-misc/qt5ct
	gui-apps/qt6ct
	x11-themes/kvantum
	media-video/vlc
	x11-themes/gtk-engines-adwaita
 	media-gfx/flameshot
	media-fonts/jetbrains-mono
	media-fonts/nerdfonts
	net-wireless/broadcom-sta
	app-emulation/spice-vdagent
	dev-qt/qtwebengine
	app-misc/fastfetch
	app-admin/calamares
	x11-themes/adw-gtk3
	x11-themes/papirus-icon-theme
	media-fonts/corefonts
	x11-themes/gentoo10-backgrounds
	x11-themes/gentoo-xcursors
	x11-themes/gentoo-artwork
	gnome-extra/yad
	gnome-extra/zenity
	x11-misc/plank
	app-editors/mousepad
	sys-libs/kpmcore
	sys-fs/jfsutils
