subarch: amd64
# version_stamp date is rewritten to the current date (MM-DD-YYYY) by autocatalyst.sh
version_stamp: stormg-08-06-2026
target: livecd-stage1
rel_type: 23.0-default
profile: default/linux/amd64/23.0/desktop
# snapshot_treeish is autodetected: autocatalyst.sh rewrites this to the
# fresh-synced gentoo tree HEAD (or --snapshot <ref>) before building
snapshot_treeish: HEAD
source_subpath: 23.0-default/stage3-amd64-desktop-openrc-latest.tar.xz
compression_mode: pixz
portage_confdir: /home/bennji/Desktop/catalyst_stormg/config/stages
repos: /home/bennji/Desktop/catalyst_stormg/overlay/var/db/repos/guru
/home/bennji/Desktop/catalyst_stormg/overlay/var/db/repos/steam-overlay
/home/bennji/Desktop/catalyst_stormg/overlay/var/db/repos/gentoo

livecd/use:
	-aac
	compile-locales
	fbcon
	jpeg2k
	livecd
	networkmanager
	openexr
	opus
	postproc
	portaudio
	pipewire
	python
	theora
	vpx
	xetex
	lvm
	contrib
	contribdnn
	lock
	ffmpeg
	extra
	geoclue
	scripttools
	positioning
	uitools
	quick
	-caja
	flatpak
	dkms
	sysprof
	-gnome
	upower
	harfbuzz

livecd/packages:
	app-admin/hddtemp
	app-admin/sudo
	app-admin/syslog-ng
	app-admin/sysstat
	app-admin/testdisk
	app-arch/bzip2
	app-arch/cpio
	app-arch/gzip
	app-arch/mt-st
	app-arch/pbzip2
	app-arch/tar
	app-arch/zip
	app-arch/unrar
	app-backup/fsarchiver
	app-cdr/dvd+rw-tools
	app-cdr/cdrtools
	app-crypt/chntpw
	app-crypt/gnupg
	app-crypt/pinentry
	app-editors/mg
	app-editors/nano
	app-editors/vim
	app-emulation/cloud-init
	app-emulation/spice-vdagent
#	Fails to build...
#	app-emulation/xen-tools
	app-eselect/eselect-repository
	app-misc/colordiff
	app-misc/livecd-tools
	app-misc/mc
	app-misc/pax-utils
	app-misc/screen
	app-misc/tmux
	app-misc/wipe
	app-portage/cpuid2cpuflags
	app-portage/eix
	app-portage/genlop
	app-portage/gentoolkit
	app-portage/mirrorselect
	app-portage/portage-utils
	app-portage/pram
	app-portage/ufed
	app-shells/bash-completion
	app-shells/gentoo-bashcomp
	app-text/bibutils
	app-text/dos2unix
	app-text/ghostscript-gpl
	app-text/pdftk
	app-text/recode
	app-text/tree
	app-text/wgetpaste
	app-text/xournalpp
	app-vim/gentoo-syntax
	dev-debug/strace
	dev-lang/perl
	dev-lang/python
	dev-python/pyqt6
#	Gone until it supports python3_10
	dev-vcs/git
	dev-vcs/subversion
	media-gfx/gimp
	media-sound/alsa-utils
	media-video/vlc
	net-analyzer/iptraf-ng
	net-analyzer/nmap
	net-analyzer/openbsd-netcat
	net-analyzer/tcpdump
	net-analyzer/tcptraceroute
	net-analyzer/traceroute
	net-dialup/minicom
	net-dialup/mingetty
	net-dialup/pptpclient
	net-dialup/rp-pppoe
	net-fs/cifs-utils
	net-fs/nfs-utils
	net-ftp/ftp
	net-ftp/ncftp
	net-im/pidgin
	net-irc/hexchat
	net-misc/chrony
	net-misc/dhcpcd
	net-misc/iputils
	net-misc/ndisc6
	net-misc/networkmanager
	net-misc/openssh
	net-misc/rdate
	net-misc/rdesktop
	net-misc/rsync
	net-misc/vconfig
	net-misc/wget
	net-misc/whois
	net-vpn/networkmanager-openvpn
	net-vpn/networkmanager-pptp
	net-vpn/openfortivpn
	net-vpn/openvpn
	net-vpn/tor
	net-wireless/b43-fwcutter
	net-wireless/iw
	net-wireless/wireless-tools
	net-wireless/wpa_supplicant
	sys-apps/arch-chroot
	sys-apps/arrayprobe
	sys-apps/acl
	sys-apps/attr
	sys-apps/busybox
	sys-apps/cciss_vol_status
	sys-apps/chname
	sys-apps/coreutils
	sys-apps/dcfldd
	sys-apps/diffutils
	sys-apps/dmidecode
	sys-apps/dstat
	sys-apps/ethtool
	sys-apps/file
	sys-apps/findutils
	sys-apps/fxload
	sys-apps/gawk
	sys-apps/gptfdisk
	sys-apps/hdparm
	sys-apps/hwinfo
	sys-apps/ipmitool
	sys-apps/iproute2
	sys-apps/inxi
	sys-apps/less
	sys-apps/man-db
	sys-apps/man-pages
	sys-apps/man-pages-posix
	sys-apps/memtester
	sys-apps/memtest86+
	sys-apps/mlocate
	sys-apps/netplug
	sys-apps/nvme-cli
	sys-apps/pciutils
	sys-apps/pcmciautils
	sys-apps/pv
	sys-apps/sdparm
	sys-apps/sed
	sys-apps/setserial
	sys-apps/sg3_utils
	sys-apps/smartmontools
	sys-apps/which
	sys-apps/usbutils
	sys-apps/util-linux
	sys-auth/ssh-import-id
	sys-block/aoetools
	sys-block/fio
	sys-block/gparted
	sys-block/mtx
	sys-block/open-iscsi
	sys-block/parted
	sys-block/partimage
	sys-block/tw_cli
	sys-block/whdd
	sys-boot/efibootmgr
	sys-boot/grub
	sys-firmware/b43-firmware
	sys-firmware/ipw2100-firmware
	sys-firmware/ipw2200-firmware
	sys-fs/bcache-tools
	sys-fs/bcachefs-tools
	sys-fs/btrfs-progs
	sys-fs/cryptsetup
	sys-fs/ddrescue
	sys-fs/dmraid
	sys-fs/dosfstools
	sys-fs/e2fsprogs
	sys-fs/exfat-utils
	sys-fs/extundelete
	sys-fs/fuse-exfat
	sys-fs/f2fs-tools
	sys-fs/genfstab
	sys-fs/growpart
	sys-fs/jfsutils
	sys-fs/lsscsi
	sys-fs/lvm2
	sys-fs/mac-fdisk
	sys-fs/mdadm
	sys-fs/multipath-tools
	sys-fs/ntfs3g
	sys-fs/reiserfsprogs
	sys-fs/squashfs-tools
	sys-fs/xfsdump
	sys-fs/xfsprogs
	sys-kernel/dracut
	sys-kernel/installkernel
	sys-kernel/linux-firmware
	sys-libs/gpm
	sys-power/acpid
	sys-process/htop
	sys-process/lsof
	sys-process/iotop
	sys-process/procps
	sys-process/psmisc
	www-client/firefox-bin
	net-print/epson-inkjet-printer-escpr
	dev-vcs/subversion
	xfce-base/xfce4-meta
	xfce-extra/xfce4-docklike-plugin
	xfce-extra/xfce4-whiskermenu-plugin
	xfce-extra/xfce4-weather-plugin
	xfce-extra/xfce4-pulseaudio-plugin
	xfce-base/xfce4-power-manager
	x11-themes/adw-gtk3
	x11-misc/lightdm
	x11-misc/lightdm-gtk-greeter
	gui-libs/display-manager-init
	gnome-extra/nm-applet
	app-cdr/xfburn
	media-gfx/ristretto
	dev-util/meld
	sys-boot/plymouth
	app-misc/fastfetch
	media-fonts/jetbrains-mono
	sys-power/upower
	acct-group/polkitd
	acct-user/polkitd
	acct-group/netdev
	app-admin/calamares
	sys-boot/grub-themes-gentoo
	sys-apps/ckbcomp
	net-wireless/broadcom-sta
	sys-firmware/b43-firmware
	sys-firmware/ipw2100-firmware
	sys-firmware/ipw2200-firmware
	sys-firmware/sof-firmware
