# created by eselect-repo

[guru]
location = /var/db/repos/guru
sync-type = git
sync-uri = https://github.com/gentoo-mirror/guru.git

[edgets]
location = /var/db/repos/edgets
sync-type = git
sync-uri = https://github.com/BlueManCZ/edgets.git

[steam-overlay]
location = /var/db/repos/steam-overlay
sync-type = git
sync-uri = https://github.com/anyc/steam-overlay.git

[zGentoo]
location = /var/db/repos/zGentoo
sync-type = git
sync-uri = https://lab.simple-co.de/zappel/zGentoo.git
