---
modules-search: [ local ]

instances:
  - id:       locale
    module:   shellprocess
    config:   shellprocess-locale.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - shellprocess@locale
      - users
      - removeuser
      - networkcfg
      - displaymanager
      - services-openrc
      - hwclock
      - grubcfg
      - bootloader
      - preservefiles
      - umount
  - show:
      - finished

branding: gentoo-xfce
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: false
quit-at-end: false
