# locale.conf
---
region: "Europe"        # set your default region
zone: "London"          # set your default zone
localeGenPath: "/etc/locale.gen"
geoipUrl: ""            # empty string disables the lookup entirely
geoipStyle: ""
