efiSystemPartition:     "/boot/efi"
userSwapChoices:
    - none
    - small
    - suspend
    - file
drawNestedPartitions:   false
alwaysShowPartitionLabels: true
allowManualPartitioning:   true
initialPartitioningChoice: none
initialSwapChoice: none
defaultFileSystemType:  "ext4"
availableFileSystemTypes:  ["ext4", "xfs", "btrfs"]
luksFileSystem: "ext4"
luksMountOptions: "noatime,discard"
