# /etc/calamares/modules/services-openrc.conf
services:
  - name: "dbus"
    mandatory: true
  - name: "elogind"
    mandatory: true
  - name: "NetworkManager"
    mandatory: false
  - name: "dmcrypt"  # For LUKS
    mandatory: false
  - name: "display-manager"
    mandatory: false
  - name: "bluetooth"
    mandatory: false