# unpackfs.conf
---
unpack:
    - source: "/mnt/cdrom/image.squashfs"
      sourcefs: "squashfs"
      destination: ""
      exclude:
          - "etc/init.d/livecd"
          - "etc/conf.d/livecd"
          - "etc/fstab"
          - "etc/hostname"
          - "etc/hosts"
          - "etc/resolv.conf"
          - "etc/udev/rules.d/70-persistent-net.rules"
          - "var/cache"
          - "var/log"
          - "tmp"
          - "root/.bashrc"
          - "home/gentoo"
          - "run"
